local.file_match "airflow_logs" {
    path_targets = [
        {
            "__path__" = "/opt/airflow/logs/dag_id=*/run_id=*/task_id=*/attempt=*.log",
            "job"      = "airflow_logs",
        },
    ]
}

local.file_match "spark_logs" {
    path_targets = [
        {
            "__path__" = "/opt/spark/logs/*/*.log",
            "job"      = "spark_logs",
        },
    ]
}

loki.source.file "airflow" {
    targets    = local.file_match.airflow_logs.targets
    forward_to = [loki.relabel.airflow.receiver]
}

loki.source.file "spark" {
    targets    = local.file_match.spark_logs.targets
    forward_to = [loki.relabel.spark.receiver]
}

loki.relabel "airflow" {
    forward_to = [loki.write.default.receiver]

    rule {
        source_labels = ["filename"]
        regex         = ".*/dag_id=([^/]+)/.*"
        target_label  = "dag_id"
    }

    rule {
        source_labels = ["filename"]
        regex         = ".*/run_id=([^/]+)/.*"
        target_label  = "run_id"
    }

    rule {
        source_labels = ["filename"]
        regex         = ".*/task_id=([^/]+)/.*"
        target_label  = "task_id"
    }

    rule {
        source_labels = ["filename"]
        regex         = ".*/attempt=([0-9]+).log"
        target_label  = "try_number"
    }
}

loki.relabel "spark" {
    forward_to = [loki.write.default.receiver]

    rule {
        source_labels = ["filename"]
        regex         = ".*/(master|worker)/.*"
        target_label  = "component"
    }
}

loki.write "default" {
    endpoint {
        url = "http://loki:3100/loki/api/v1/push"
    }
}
