name: Lab3 CI/CD

on:
  push:
    branches:
      - "**"
  
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - clear

jobs:

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Check folders
        run: |
          echo "Checking dags and spark..."
          test -d dags || (echo "No dags folder!" && exit 1)
          test -d spark || (echo "No spark folder!" && exit 1)

  build:
    runs-on: ubuntu-22.04
    needs: test

    if: |
      (github.event_name == 'push' && !startsWith(github.ref, 'refs/heads/feature/')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy')

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t devops-aith .

  deploy:
    runs-on: ubuntu-22.04
    needs: build

    if: |
      (github.event_name == 'push' &&
        (github.ref == 'refs/heads/main' ||
         github.ref == 'refs/heads/master' ||
         github.ref == 'refs/heads/develop' ||
         github.ref == 'refs/heads/lab-03')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy')

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying..."
          docker compose up -d
          docker ps

  clear:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'clear'

    steps:
      - uses: actions/checkout@v4
      
      - name: Clear
        run: |
          echo "Cleaning up..."
          docker compose down
          docker system prune -f
          echo "Cleanup complete"

